config/routes.rb
NuxWS::Application.routes.draw do
  resources :mailings

  resources :pms do
    get "mark_read", :to => "pms#mark_read"
  end

  match "/donations/ipn", :to => "donations#ipn"
  match "/donations/thanks", :to => "donations#thanks"
  match "/donations/cancel", :to => "donations#cancel"
  match "/donations/list", :to => "donations#list"
  resources :donations

  resources :users do
    get "messages", :to => "users#messages"
    get "topics", :to => "users#topics"
    get "topics_notifications", :to => "users#topics_notifications"
  end
  resources :user_sessions
  resources :places
  match "/forums/mark_all_read", :to => "forums#mark_all_read"
  resources :forums do
    resources :topics do
      match :pin, :to => "topics#pin"
      match :unpin, :to => "topics#unpin"
      match :lock, :to => "topics#lock"
      match :unlock, :to => "topics#unlock"
      match :follow, :to => "topics#follow"
      match :unfollow, :to => "topics#unfollow"
      resources :messages
    end
  end
  resources :settings
  resources :galleries do
    resources :images
  end
  resources :docs
  resources :forum_categories
  resources :logs

  resources :password_resets, :only => [ :new, :create, :edit, :update ]
  resources :search

  # ADMIN PART
  # This is the admin part, some are non-restfull 'cause they can't be restfull.
  # This is not really database-backend but API calls...
  get "/admin", :to => "admin#index"
  namespace :admin do
    resources :worlds, :only => [:index] do
      post "set_time", :to => "worlds#set_time"
    end
    resources :plugins, :only => [:index]
  end
  # END ADMIN PART


  match "/login", :to => "user_sessions#new"
  match "/logout", :to => "user_sessions#destroy"
  match "/settings", :to => "settings#update", :via => :put
  match "/pony", :to => "application#pony", :via => :get

  root :to => "application#index"

end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
  end

  def show
    ctrl = "index"
    if params[:id] == "topics_title"
      @topics = Topic.where(:title.like "%#{params[:q_title]}%").page(params[:page]).per(20)
      ctrl = :topics

    elsif params[:id] == "topics_msg"
      @topics = Topic.where(:content.like "%#{params[:q_msg]}%").page(params[:page]).per(20)
      ctrl = :topics

    elsif params[:id] == "messages"
      @messages = Message.where(:content.like "%#{params[:q_msg]}%").page(params[:page]).per(20)
      ctrl = :messages

    elsif params[:id] == "docs_desc"
      @docs = Doc.where(:description.like "%#{params[:q_desc]}%").page(params[:page]).per(20)
      ctrl = :docs

    elsif params[:id] == "docs_content"
      @docs = Doc.where(:content.like "%#{params[:q_content]}%").page(params[:page]).per(20)
      ctrl = :docs

    elsif params[:id] == "places_shortdesc"
      @places = Place.where(:short_description.like "%#{params[:q_shortdesc]}%").page(params[:page]).per(20)
      ctrl = :places

    elsif params[:id] == "places_desc"
      @places = Place.where(:description.like "%#{params[:q_desc]}%").page(params[:page]).per(20)
      ctrl = :places

    elsif params[:id] == "galleries_title"
      @galleries = Gallery.where(:title.like "%#{params[:q_title]}%").page(params[:page]).per(20)
      ctrl = :galleries

    elsif params[:id] == "galleries_desc"
      @galleries = Gallery.where(:description.like "%#{params[:q_desc]}%").page(params[:page]).per(20)
      ctrl = :galleries

    elsif params[:id] == "images_title"
      @images = Image.where(:title.like "%#{params[:q_title]}%").page(params[:page]).per(20)
      ctrl = :images

    elsif params[:id] == "images_desc"
      @images = Image.where(:description.like "%#{params[:q_desc]}%").page(params[:page]).per(20)
      ctrl = :images

    else
      return redirect_to search_url
    end
    return render ctrl
  end
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/search/docs.html.erb
<%- model_class = Doc.new.class -%>
<h1>Documents search</h1>
<table class="table table-striped table-condensed">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @docs.each do |doc| %>
      <tr>
        <td><%= link_to doc.title, doc_path(doc) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @docs %>

app/views/search/galleries.html.erb
<%- model_class = Gallery.new.class -%>
<h1>Galleries search</h1>
<table class="table table-striped table-condensed">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @galleries.each do |gallery| %>
      <tr>
        <td><%= link_to gallery.title, gallery_path(gallery) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @galleries %>

app/views/search/images.html.erb
<%- model_class = Image.new.class -%>
<h1>Images search</h1>
<table class="table table-striped table-condensed">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @images.each do |image| %>
      <tr>
        <td><%= link_to image.title, gallery_image_path(image.gallery, image) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @images %>

app/views/search/index.html.erb
<div class="row">
  <div class="span4 offset2">
    <h3>Topics</h3>
    <%= form_tag search_url(:topics_title), :method => "GET", :class => "form-horizontal" do %>
      <%= label_tag :q_title, "Title:" %>
      <%= text_field_tag :q_title %>
      <%= submit_tag :search %>
    <% end %>
    <%= form_tag search_url(:topics_msg), :method => "GET", :class => "form-horizontal" do %>
      <%= label_tag :q_msg, "Message:" %>
      <%= text_field_tag :q_msg %>
      <%= submit_tag :search %>
    <% end %>
  </div>

  <div class="span4">
    <h3>Messages</h3>
    <%= form_tag search_url(:messages), :method => "GET", :class => "form-horizontal" do %>
      <%= label_tag :q_msg, "Message:" %>
      <%= text_field_tag :q_msg %>
      <%= submit_tag :search %>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="span4 offset2">
    <h3>Documents</h3>
    <%= form_tag search_url(:docs_desc), :method => "GET", :class => "form-horizontal" do %>
      <%= label_tag :q_desc, "Description:" %>
      <%= text_field_tag :q_desc %>
      <%= submit_tag :search %>
    <% end %>
    <%= form_tag search_url(:docs_content), :method => "GET", :class => "form-horizontal" do %>
      <%= label_tag :q_content, "Contenu:" %>
      <%= text_field_tag :q_content %>
      <%= submit_tag :search %>
    <% end %>
  </div>

  <div class="span4">
    <h3>Lieux</h3>
    <%= form_tag search_url(:places_shortdesc), :method => "GET", :class => "form-horizontal" do %>
      <%= label_tag :q_shortdesc, "Short description:" %>
      <%= text_field_tag :q_shortdec %>
      <%= submit_tag :search %>
    <% end %>
    <%= form_tag search_url(:places_desc), :method => "GET", :class => "form-horizontal" do %>
      <%= label_tag :q_desc, "Descripion:" %>
      <%= text_field_tag :q_desc %>
      <%= submit_tag :search %>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="span4 offset2">
    <h3>Galleries</h3>
    <%= form_tag search_url(:galleries_title), :method => "GET", :class => "form-horizontal" do %>
      <%= label_tag :q_title, "Title:" %>
      <%= text_field_tag :q_title %>
      <%= submit_tag :search %>
    <% end %>
    <%= form_tag search_url(:galleries_desc), :method => "GET", :class => "form-horizontal" do %>
      <%= label_tag :q_desc, "Description:" %>
      <%= text_field_tag :q_desc %>
      <%= submit_tag :search %>
    <% end %>
  </div>

  <div class="span4">
    <h3>Images</h3>
    <%= form_tag search_url(:images_title), :method => "GET", :class => "form-horizontal" do %>
      <%= label_tag :q_title, "Title:" %>
      <%= text_field_tag :q_title %>
      <%= submit_tag :search %>
    <% end %>
    <%= form_tag search_url(:images_desc), :method => "GET", :class => "form-horizontal" do %>
      <%= label_tag :q_desc, "Description:" %>
      <%= text_field_tag :q_desc %>
      <%= submit_tag :search %>
    <% end %>
  </div>
</div>

app/views/search/messages.html.erb
<%- model_class = Message.new.class -%>
<h1>Message search</h1>
<table class="table table-striped table-condensed">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:content) %></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @messages.each do |msg| %>
      <tr>
        <td><%= link_to msg.title, forum_topic_path(msg.topic.forum, msg.topic) %></td>
        <td><%= raw msg.content.bbcode_to_html %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @messages %>

app/views/search/places.html.erb
<%- model_class = Place.new.class -%>
<h1>Places search</h1>
<table class="table table-striped table-condensed">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @places.each do |place| %>
      <tr>
        <td><%= link_to place.name, place_path(place) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @places %>

app/views/search/topics.html.erb
<%- model_class = Topic.new.class -%>
<h1>Topic search</h1>
<table class="table table-striped table-condensed">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:content) %></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @topics.each do |topic| %>
      <tr>
        <td><%= link_to topic.title, forum_topic_path(topic.forum, topic) %></td>
        <td><%= topic.content %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @topics %>