config/routes.rb
NuxWS::Application.routes.draw do
  resources :mailings

  resources :pms do
    get "mark_read", :to => "pms#mark_read"
  end

  match "/donations/ipn", :to => "donations#ipn"
  match "/donations/thanks", :to => "donations#thanks"
  match "/donations/cancel", :to => "donations#cancel"
  match "/donations/list", :to => "donations#list"
  resources :donations

  resources :users do
    get "messages", :to => "users#messages"
    get "topics", :to => "users#topics"
    get "topics_notifications", :to => "users#topics_notifications"
  end
  resources :user_sessions
  resources :places
  match "/forums/mark_all_read", :to => "forums#mark_all_read"
  resources :forums do
    resources :topics do
      match :pin, :to => "topics#pin"
      match :unpin, :to => "topics#unpin"
      match :lock, :to => "topics#lock"
      match :unlock, :to => "topics#unlock"
      match :follow, :to => "topics#follow"
      match :unfollow, :to => "topics#unfollow"
      resources :messages
    end
  end
  resources :settings
  resources :galleries do
    resources :images
  end
  resources :docs
  resources :forum_categories
  resources :logs

  resources :password_resets, :only => [ :new, :create, :edit, :update ]
  resources :search

  # ADMIN PART
  # This is the admin part, some are non-restfull 'cause they can't be restfull.
  # This is not really database-backend but API calls...
  get "/admin", :to => "admin#index"
  namespace :admin do
    resources :worlds, :only => [:index] do
      post "set_time", :to => "worlds#set_time"
    end
    resources :plugins, :only => [:index]
  end
  # END ADMIN PART


  match "/login", :to => "user_sessions#new"
  match "/logout", :to => "user_sessions#destroy"
  match "/settings", :to => "settings#update", :via => :put
  match "/pony", :to => "application#pony", :via => :get

  root :to => "application#index"

end

app/models/topic.rb
class Topic < ActiveRecord::Base
  attr_accessible :title, :content, :username, :created_at, :last_message_at, :forum_id

  validates_presence_of :title, :content

  # Default scope : pinnned at top then latest created at top

  acts_as_readable :on => :last_message_at

  extend FriendlyId
  friendly_id :title, use: :slugged

  paginates_per Settings.pagination_topics.to_i

  belongs_to :forum
  belongs_to :user
  has_many :messages, :dependent => :delete_all
  has_many :topic_notifications, :dependent => :delete_all

  before_create :update_last_message_at

  def update_last_message_at
    self.last_message_at = Time.now
  end

  def anonymous?
    !self.username.blank?
  end

  def pin!
    self.pin = true
    self.save
  end
  def unpin!
    self.pin = false
    self.save
  end

  def lock!
    self.locked = true
    self.save
  end
  def unlock!
    self.locked = false
    self.save
  end

  def can_edit?(cur_user)
    return true if cur_user.admin?
    return false if (Time.now - self.updated_at) >= 4.hours
    return true
  end

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  load_and_authorize_resource :forum
  load_and_authorize_resource :topic, :through => :forum

  before_filter :at_least_modo, :only => [:pin, :unpin, :lock, :unlock]

  # GET /topics
  # GET /topics.json
  def index
    @forum = Forum.find(params[:forum_id])
    redirect_to @forum
  end

  # GET /topics/xxx
  # GET /topics/xxx.json
  def show
    @forum = Forum.find(params[:forum_id])
    @messages = @topic.messages.accessible_by(current_ability).page params[:page]
    @feed_link = forum_topic_url(@forum, @topic, :format => :atom)

    if current_user
      @topic.mark_as_read! :for => current_user
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @topic }
      format.atom { render :layout => false }
    end
  end

  # GET /topics/new
  # GET /topics/new.json
  def new
    @forum = Forum.find(params[:forum_id])

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @topic }
    end
  end

  # GET /topics/xxx/edit
  def edit
    @forum = Forum.find(params[:forum_id])
    #@topic = Topic.find(params[:id])
  end

  # POST /topics
  # POST /topics.json
  def create
    @forum = Forum.find(params[:forum_id])

    @topic.forum = @forum
    @topic.user = current_user
    @topic.moderation = true if current_user.role <= Role.get_id(:guest)

    respond_to do |format|
      if @topic.save
        format.html { redirect_to [@forum, @topic], notice: 'Topic was successfully created.' }
        format.json { render json: @topic, status: :created, location: @topic }
      else
        format.html { render action: "new" }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /topics/xxx
  # PUT /topics/.json
  def update
    @forum = Forum.find(params[:forum_id])

    params[:user_id] = current_user.id
    params[:forum_id] = @forum.id
    params[:moderation] = true if current_user.role <= Role.get_id(:guest)

    respond_to do |format|
      if @topic.update_attributes(params[:topic])
        format.html { redirect_to [@forum, @topic], notice: 'Topic was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/xxx
  # DELETE /topics/xxx.json
  def destroy
    @forum = Forum.find(params[:forum_id])
    @topic.destroy

    respond_to do |format|
      format.html { redirect_to forum_url(@forum) }
      format.json { head :no_content }
    end
  end

  # Pin and Lock functions
  def pin
    @forum = Forum.find(params[:forum_id])
    @topic = Topic.find(params[:topic_id])
    @topic.pin!

    respond_to do |format|
      format.html { redirect_to forum_topic_url(@forum, @topic), notice: 'Topic was successfully pinned.' }
      format.json { head :no_content }
    end
  end
  def unpin
    @forum = Forum.find(params[:forum_id])
    @topic = Topic.find(params[:topic_id])
    @topic.unpin!

    respond_to do |format|
      format.html { redirect_to forum_topic_url(@forum, @topic), notice: 'Topic was successfully un-pin.' }
      format.json { head :no_content }
    end
  end
  def lock
    @forum = Forum.find(params[:forum_id])
    @topic = Topic.find(params[:topic_id])
    @topic.lock!

    respond_to do |format|
      format.html { redirect_to forum_topic_url(@forum, @topic),notice: 'Topic was successfully locked.' }
      format.json { head :no_content }
    end
  end
  def unlock
    @forum = Forum.find(params[:forum_id])
    @topic = Topic.find(params[:topic_id])
    @topic.unlock!

    respond_to do |format|
      format.html { redirect_to forum_topic_url(@forum, @topic), notice: 'Topic was successfully unlocked.' }
      format.json { head :no_content }
    end
  end

  def follow
    @forum = Forum.find(params[:forum_id])
    @topic = Topic.find(params[:topic_id])
    relation = TopicNotification.where(:topic_id => @topic.id, :user_id => current_user.id)
    if relation.count == 0
      TopicNotification.create(:topic_id => @topic.id, :user_id => current_user.id)
    end
    return redirect_to forum_topic_url(@forum, @topic), notice: 'You are now following this topic.'
  end

  def unfollow
    @forum = Forum.find(params[:forum_id])
    @topic = Topic.find(params[:topic_id])
    relation = TopicNotification.where(:topic_id => @topic.id, :user_id => current_user.id)
    relation.each do |rel|
      rel.destroy
    end
    redirect_to forum_topic_url(@forum, @topic), notice: 'You are not following this topic anymore.'
  end

end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<%= form_for [@forum, @topic], :html => { :class => 'form-horizontal well' } do |f| %>
  <% if @topic.errors.any? %>
    <div id="error_explanation">
      <h3><%= pluralize(@topic.errors.count, "error") %> prohibited this topic from being saved:</h3>

      <ul>
		  <% @topic.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :title, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'text_field', :class => "span6" %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :content, :class => 'control-label' %>
    <div class="controls" style="display: inline-block;">
      <%= f.text_area :content, :class => 'text_field', :rows => 10, :cols => 20, :class => "markItUp-bbcode" %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary btn-mini' %>
	<%- if @topic.new_record? %>
	<%= link_to content_tag(:i, "", :class => "icon-remove") + " " + t('.cancel', :default => t("helpers.links.cancel")), forum_path(@forum), :class => 'btn btn-mini' %>
	<% else %>
	<%= link_to content_tag(:i, "", :class => "icon-remove") +  " " + t('.cancel', :default => t("helpers.links.cancel")), forum_topic_path(@forum, @topic), :class => 'btn btn-mini' %>
	<% end %>
  </div>
<% end %>

app/views/topics/_msg.html.erb
<div class="row block_message" id="msg_id_<%= msg.id %>">
	<!-- 9 usable columns, two last are for last topics unread -->
	<div class="span9 topic_block">
		<div class="row">
			<div class="span2 tb_author">
				<img class="tb_skin skin pull-left" src="https://minotar.net/avatar/<%= msg.user ? msg.user.login : msg.username %>/40.png"/>

        <h4>
          <%- if msg.user %>
				    <%= link_to msg.user.login, msg.user %>
          <% else %>
            <%= msg.username %>
          <% end %>
        </h4>
				<% if msg.user && !msg.user.custom_role.blank? %><%= msg.user.custom_role %><br /><% end %>
				<i class="icon-asterisk"></i> <%= msg.user ? msg.user.role_name : "anonymous" %><br />

				<%= t '.messages_count', :number => (msg.user ? msg.user.messages.count : 0 )%><br />
			</div>

			<div class="span7 tb_msg">
				<div class="row tb_msg_dating">
					<div class="span5">
						<%- if !topic %>
						<h4><%= link_to msg.title, :anchor => "msg_id_#{msg.id}" %></h4>
						<% end %>
						<%- if !topic %>&nbsp;&nbsp;&nbsp;<% end %><b>le:</b> <%= ftime(msg.created_at) %>
					</div>
					<div class="span2">
						<%- if topic %>
						<%= link_to content_tag(:i, "", :class => "icon-pencil") + " Éditer", edit_forum_topic_path(@forum, @topic), :class => "btn btn-mini" if (can?(:edit, @topic) and @topic.can_edit?(current_user)) %>
						<%= link_to content_tag(:i, "", :class => "icon-trash") + " " + t('.destroy', :default => t("helpers.links.destroy")),
						forum_topic_path(@forum, @topic),
						:method => :delete,
						:confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
						:class => 'btn btn-mini btn-danger' if can?(:destroy, @topic) %>
						<% else %>
						<%= link_to content_tag(:i, "", :class => "icon-pencil") + " Éditer", edit_forum_topic_message_path(@forum, @topic, msg), :class => "btn btn-mini" if (can?(:edit, msg) and msg.can_edit?(current_user)) %>
						<%= link_to content_tag(:i, "", :class => "icon-trash") + " " + t('.destroy', :default => t("helpers.links.destroy")),
						forum_topic_message_path(@forum, @topic, msg),
						:method => :delete,
						:confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
						:class => 'btn btn-mini btn-danger' if can?(:destroy, msg) %>
						<% end %>
					</div>
				</div>

				<div class="row tb_msg_content">
					<div class="span7">
            <%- if !msg.user && !msg.username.blank? %>
              <%= raw msg.content.bbcode_to_html({}, false) %>
            <% else %>
              <%= raw msg.content.bbcode_to_html %>
            <% end %>
						<% if msg.user && !msg.user.signature.blank? %>
						<hr>
						<%= raw msg.user.signature.bbcode_to_html %>
						<% end %>
					</div>
				</div>

			</div> <!-- span2 tb_msg -->
		</div>
	</div>
</div>

app/views/topics/_msg_deleted.html.erb
<div class="row block_message">
	<!-- 9 usable columns, two last are for last topics unread -->
	<div class="span9 offset1 topic_block">
		<div class="row">
			<div class="span2 tb_author">
				<h4><%= link_to msg.user.login, msg.user %></h4>
			</div>
			<div class="span3 tb_date">
				<b><%= t '.at' %></b> <%= ftime(msg.created_at) %>
			</div>
			<div class="span3 tb_deleted">
				<b><%= t '.message_deleted' %></b> <i><%= msg.deletion_reason %></i>
			</div>
			<div class="span1 tb_edit">
				<%= link_to content_tag(:i, "", :class => "icon-pencil") + " " + t('.edit', :default => t("helpers.links.edit")), edit_forum_topic_message_path(@forum, @topic, msg), :class => "btn btn-mini" if can?(:edit, msg) %>
			</div>
		</div>
	</div>
</div>

app/views/topics/edit.html.erb
<div class="row">
	<div class="span10 offset1">
		<h2><%= link_to @forum.title, @forum %> &raquo; <small><%= link_to @topic.title, [@forum, @topic] %></small></h2>
		<br />
		<%= render :partial => 'form' %>
	</div>
</div>

app/views/topics/new.html.erb
<div class="row">
	<div class="span10 offset1">
		<h1><%= t '.title' %></h1>
		<br />
		<%= render :partial => 'form' %>
	</div>
</div>

app/views/topics/show.html.erb
<div class="row">
	<div class="span8">
		<h2><%= link_to @forum.title, @forum %> &raquo; <small><%= @topic.title %></small></h2>
	</div>
	<div class="span4">
		<%= link_to content_tag(:i, "", :class => "icon-comment") + " " + t('.answer'), new_forum_topic_message_path(@forum, @topic), :class => "btn btn-mini" if can?(:create, Message) %>

		<% if @current_user %>

		<% if TopicNotification.where(:user_id => @current_user.id, :topic_id => @topic.id).count == 1 %>
		<%= link_to content_tag(:i, "", :class => "icon-remove-sign") + " " + t('.unfollow'), forum_topic_unfollow_path(@forum, @topic), :class => "btn btn-mini" %>
		<% else %>
		<%= link_to content_tag(:i, "", :class => "icon-ok-sign") + " " + t('.follow'), forum_topic_follow_path(@forum, @topic), :class => "btn btn-mini" %>
		<% end %>

		<% if @current_user.at_least_modo? %>
		<%- if @topic.locked %>
		<%= link_to content_tag(:i, "", :class => "icon-lock") + " " + t('.unlock'), forum_topic_unlock_path(@forum, @topic), :class => "btn btn-mini" if can?(:edit, @topic) %>
		<% else %>
		<%= link_to content_tag(:i, "", :class => "icon-lock") + " " + t('.lock'), forum_topic_lock_path(@forum, @topic), :class => "btn btn-mini" if can?(:edit, @topic) %>
		<% end %>

		<%- if @topic.pin %>
		<%= link_to content_tag(:i, "", :class => "icon-flag") + " " + t('.unpin'), forum_topic_unpin_path(@forum, @topic), :class => "btn btn-mini" if can?(:edit, @topic) %>
		<% else %>
		<%= link_to content_tag(:i, "", :class => "icon-flag") + " " + t('.pin'), forum_topic_pin_path(@forum, @topic), :class => "btn btn-mini" if can?(:edit, @topic) %>
		<% end %>
		<% end %>
		<% end %>

	</div>
</div>

<br />

<div class="row">
	<div class="span10">
<div class="row">
	<!-- 9 usable columns, two last are for last topics unread -->
	<div class="span9 topic_header">
		<div class="row">
			<div class="span2 th_author">
				<h4><%= t '.author' %></h4>
			</div>
			<div class="span7">
				<h4><%= t '.subject', :title => @topic.title %></h4>
			</div>
		</div>
	</div>
</div>


<%= render :partial => "msg", :locals => {:topic => @topic, :msg => @topic} %>

<br />

<%- @messages.each do |message| %>
<%- if message.deleted %>
<%= render :partial => "msg_deleted", :locals => {:msg => message} %>
<% else %>
<%= render :partial => "msg", :locals => {:topic => nil, :msg => message} %>
<% end %>
<% end %>

</div>
	<div class="span2">
		<%= render :partial => 'forums/sidebar' %>
	</div>
	</div>

<%= paginate @messages %>