config/routes.rb
NuxWS::Application.routes.draw do
  resources :mailings

  resources :pms do
    get "mark_read", :to => "pms#mark_read"
  end

  match "/donations/ipn", :to => "donations#ipn"
  match "/donations/thanks", :to => "donations#thanks"
  match "/donations/cancel", :to => "donations#cancel"
  match "/donations/list", :to => "donations#list"
  resources :donations

  resources :users do
    get "messages", :to => "users#messages"
    get "topics", :to => "users#topics"
    get "topics_notifications", :to => "users#topics_notifications"
  end
  resources :user_sessions
  resources :places
  match "/forums/mark_all_read", :to => "forums#mark_all_read"
  resources :forums do
    resources :topics do
      match :pin, :to => "topics#pin"
      match :unpin, :to => "topics#unpin"
      match :lock, :to => "topics#lock"
      match :unlock, :to => "topics#unlock"
      match :follow, :to => "topics#follow"
      match :unfollow, :to => "topics#unfollow"
      resources :messages
    end
  end
  resources :settings
  resources :galleries do
    resources :images
  end
  resources :docs
  resources :forum_categories
  resources :logs

  resources :password_resets, :only => [ :new, :create, :edit, :update ]
  resources :search

  # ADMIN PART
  # This is the admin part, some are non-restfull 'cause they can't be restfull.
  # This is not really database-backend but API calls...
  get "/admin", :to => "admin#index"
  namespace :admin do
    resources :worlds, :only => [:index] do
      post "set_time", :to => "worlds#set_time"
    end
    resources :plugins, :only => [:index]
  end
  # END ADMIN PART


  match "/login", :to => "user_sessions#new"
  match "/logout", :to => "user_sessions#destroy"
  match "/settings", :to => "settings#update", :via => :put
  match "/pony", :to => "application#pony", :via => :get

  root :to => "application#index"

end

app/views/admin/_navbar.html.erb
<div class="navbar row">
  <div class="navbar-inner">
    <%= link_to "Admin", admin_url, :class => "brand" %>
    <ul class="nav">
      <li class="<%= @cur_tab == :worlds ? 'active' : '' %>" ><%= link_to "Mondes", admin_worlds_url %></li>
      <li class="<%= @cur_tab == :players ? 'active' : '' %>" ><%= link_to "Joueurs", "" %></li>
      <li class="<%= @cur_tab == :plugins ? 'active' : '' %>" ><%= link_to "Plugins", admin_plugins_url %></li>
    </ul>
  </div>
</div>

app/views/admin/index.html.erb
<%= render :partial => "admin/navbar" %>

<%- if @jsonapi[:getServer] %>
  MaxPlayers : <%= @jsonapi[:getServer]["maxPlayers"] %><br />
  Name : <%= @jsonapi[:getServer]["name"] %><br />
  ServerName : <%= @jsonapi[:getServer]["serverName"] %><br />
  Version : <%= @jsonapi[:getServer]["version"] %><br />
<% else %>
  No API response from server.
<% end %>